apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-service-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: booking.cegove.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: booking-service-svc
                port:
                  number: 80
  tls:
    - hosts:
        - booking.cegove.cloud
      secretName: booking-service-tls