services:
  app:
    build: .
    container_name: payment_service
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/payment_service.db
      - VNPAY_TMN_CODE=${VNPAY_TMN_CODE}
      - VNPAY_HASH_SECRET=${VNPAY_HASH_SECRET}
      - VNPAY_PAYMENT_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - VNPAY_RETURN_URL=${VNPAY_RETURN_URL:-http://localhost:8000/api/v1/webhooks/vnpay/return}
      - VNPAY_IPN_URL=${VNPAY_IPN_URL:-http://localhost:8000/api/v1/webhooks/vnpay/ipn}
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
